#!/usr/bin/env bash
# Install muse-dev-skills into Claude Code (home) and/or Devin Desktop née Windsurf (work).
#
#   ./install.sh claude              # → ~/.claude/skills/
#   ./install.sh windsurf <repo>     # → <repo>/.windsurf/{skills,workflows,rules}/ + local .agent/ ignore
#   ./install.sh windsurf-global     # → ~/.codeium/windsurf/{skills,global_workflows}/
#
# SKILL.md is the single source of truth. Both Claude Code and Devin Desktop read the
# same files natively (Devin scans .windsurf/skills/, .devin/skills/, .agents/skills/,
# .claude/skills/ and four more). The workflow files are 6-line shims that just invoke
# the matching skill — they exist only so /brief-style slash commands keep working on
# the legacy Cascade agent, which cannot auto-invoke skills. Devin Local does not
# support workflows at all; it runs the skills directly.
#
# RE-RUNNING THIS IS THE SUPPORTED UPGRADE PATH. Every target replaces the skills it
# manages, and prunes skills it installed on a PREVIOUS run that this version no longer
# ships (renamed/retired), so no ghost skill survives an upgrade and keeps firing.
# Skills that were never installed by this script are left untouched.
set -euo pipefail
cd "$(dirname "$0")"

SKILLS=(feature-brief domain-tutor impl-log explain-before-merge spring-ai-mentor
        token-sniper standup-reporter stuck-protocol vaadin-mentor copilot-bridge
        brainstorm task-planner code-cartographer flow-tracer
        corrections-ledger precedent-check architecture-contract demo-prep)

VERSION_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
VERSION_DATE="$(git log -1 --format=%cI 2>/dev/null || echo unknown)"
INSTALLED_AT="$(date +%Y-%m-%dT%H:%M:%S%z)"

# prune_orphans <skills-dir> <manifest-file>
# Remove skills a previous run of THIS script installed that the current version no
# longer ships. Anything absent from the old manifest is foreign and is never touched.
prune_orphans() {
  local dir="$1" manifest="$2" old
  [ -f "$manifest" ] || return 0
  for old in $(sed -n 's/^skills=//p' "$manifest"); do
    case " ${SKILLS[*]} " in
      *" $old "*) ;;
      *) if [ -d "$dir/$old" ]; then rm -rf "${dir:?}/$old"; echo "Pruned retired skill: $old"; fi ;;
    esac
  done
}

# write_manifest <manifest-file> <target-label>
write_manifest() {
  local manifest="$1" target="$2"
  mkdir -p "$(dirname "$manifest")"
  cat > "$manifest" <<EOF
# muse-dev-skills install manifest — generated by install.sh, do not edit
version_sha=$VERSION_SHA
version_date=$VERSION_DATE
installed_at=$INSTALLED_AT
target=$target
skills=${SKILLS[*]}
EOF
}

case "${1:-}" in
  claude)
    dir=~/.claude/skills
    manifest="$dir/.muse-manifest"
    mkdir -p "$dir"
    prune_orphans "$dir" "$manifest"
    # remove previous copies first so files renamed/deleted upstream don't linger
    for s in "${SKILLS[@]}"; do rm -rf "$dir/$s"; cp -r "$s" "$dir/"; done
    write_manifest "$manifest" claude
    echo "Installed ${#SKILLS[@]} skills to $dir/ (old copies replaced, version $VERSION_SHA)."
    ;;
  windsurf)
    repo="${2:?usage: ./install.sh windsurf <path-to-work-repo>}"
    manifest="$repo/.agent/muse-manifest"
    mkdir -p "$repo/.windsurf/skills" "$repo/.windsurf/workflows" "$repo/.windsurf/rules" "$repo/.agent/reference"
    # drop skills a previous run installed that this version retired, so a renamed or
    # removed skill can't survive as a ghost that still fires
    prune_orphans "$repo/.windsurf/skills" "$manifest"
    # skills: replace only the ones this repo manages, by name — never wipe the whole
    # dir, so any skill created directly in the work repo survives an update
    for s in "${SKILLS[@]}"; do rm -rf "$repo/.windsurf/skills/$s"; cp -r "$s" "$repo/.windsurf/skills/"; done
    # workflows + rules are fully managed here — wipe stale *.md so renamed/removed
    # files don't survive as ghost slash-commands
    rm -f "$repo/.windsurf/workflows"/*.md "$repo/.windsurf/rules"/*.md
    cp windsurf/workflows/*.md "$repo/.windsurf/workflows/"
    cp windsurf/rules/*.md     "$repo/.windsurf/rules/"
    # pattern references — readable as workspace files (see the spring-ai / vaadin rules)
    cp spring-ai-mentor/references/spring-ai-patterns.md \
       vaadin-mentor/references/vaadin-patterns.md \
       token-sniper/references/weak-model-playbook.md \
       copilot-bridge/assets/copilot-session-prompts.md \
       "$repo/.agent/reference/"
    cp copilot-bridge/scripts/context-pack.sh "$repo/.agent/"
    chmod +x "$repo/.agent/context-pack.sh"
    # Copilot custom-agent templates — refined in-place at work (see agents/README.md)
    # refresh templates only; NEVER touch *.refined.md (work-side refinements)
    mkdir -p "$repo/.agent/reference/copilot-agents"
    find "$repo/.agent/reference/copilot-agents" -maxdepth 1 -name '*.md' ! -name '*.refined.md' -delete
    cp copilot-bridge/agents/*.md "$repo/.agent/reference/copilot-agents/"
    if [ -d "$repo/.git" ] && ! grep -q '^\.agent/$' "$repo/.git/info/exclude" 2>/dev/null; then
      echo ".agent/" >> "$repo/.git/info/exclude"
      echo "Added .agent/ to $repo/.git/info/exclude (local-only ignore)."
    fi
    write_manifest "$manifest" "windsurf:$repo"
    echo "Installed ${#SKILLS[@]} skills + $(ls windsurf/workflows/*.md | wc -l | tr -d ' ') workflow shims + $(ls windsurf/rules/*.md | wc -l | tr -d ' ') rules into $repo/.windsurf/,"
    echo "references + context-pack.sh into $repo/.agent/ (version $VERSION_SHA)."
    echo "Manifest: $manifest"
    echo "Invoke with /brainstorm /brief /plan /precedent /arch /verify /log /trace /map /tutor /stuck /standup /ledger /demo /sniper /bridge."
    ;;
  windsurf-global)
    dir=~/.codeium/windsurf/skills
    manifest=~/.codeium/windsurf/.muse-manifest
    mkdir -p "$dir" ~/.codeium/windsurf/global_workflows
    prune_orphans "$dir" "$manifest"
    for s in "${SKILLS[@]}"; do rm -rf "$dir/$s"; cp -r "$s" "$dir/"; done
    cp windsurf/workflows/*.md ~/.codeium/windsurf/global_workflows/
    write_manifest "$manifest" windsurf-global
    echo "Installed ${#SKILLS[@]} skills to $dir/ and shims to global_workflows/ (all projects, version $VERSION_SHA)."
    ;;
  *)
    echo "usage: ./install.sh claude | windsurf <path-to-work-repo> | windsurf-global" >&2
    exit 1
    ;;
esac
